name: Platform Lint, Build & Test (CI)

on:
  push:
    branches: [main]
  pull_request:
    branches: ['main']

jobs:
  lint_test_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.16.0
      - run: npm ci
      - run: npm run lint:check
      - run: npm run format:check
      - run: npm run test:cov
      - run: npm run build
